import { Archive, ArchiveRestore, ArrowLeft, CalendarClock, Settings2 } from "lucide-react";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";

import { ActionMenu } from "@/components/action-menu";
import { EmptyState, ErrorState } from "@/components/feedback";
import { MoneyValue } from "@/components/money-value";
import { ConfirmDialog } from "@/components/sheet";
import { CardDetailSkeleton, StatementsSkeleton } from "@/components/skeletons";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/toast";
import { useCard, useCardCurrentCycle, useCardStatements, useSetCardActive } from "@/hooks/use-cards";
import { formatFinancialDate } from "@/lib/dates";
import { toUserMessage } from "@/lib/errors";
import type { CardStatement } from "@/types/database";
import { CardFormSheet } from "@/features/cards/card-form-sheet";
import { cardThemes, cardUtilization } from "@/features/cards/card-utils";
import { CloseStatementDialog } from "@/features/cards/close-statement-dialog";
import { StatementDetailSheet } from "@/features/cards/statement-detail-sheet";

export function CardDetailPage() {
  const { id } = useParams(); const card = useCard(id); const cycle = useCardCurrentCycle(id); const statements = useCardStatements(id); const setActive = useSetCardActive(); const toast = useToast();
  const [editOpen, setEditOpen] = useState(false); const [archiveOpen, setArchiveOpen] = useState(false); const [closeOpen, setCloseOpen] = useState(false); const [selected, setSelected] = useState<CardStatement>();
  if (card.isPending) return <CardDetailSkeleton />;
  if (card.isError || !card.data) return <ErrorState message={toUserMessage(card.error)} onRetry={() => void card.refetch()} />;
  const current = card.data; const utilization = cardUtilization(current.used_balance_minor, current.credit_limit_minor); const theme = cardThemes[current.visual_theme];
  async function toggleActive(active: boolean) { try { await setActive.mutateAsync({ cardId: current.id, active }); toast.success(active ? "Tarjeta restaurada" : "Tarjeta archivada"); setArchiveOpen(false); } catch (error) { toast.error(toUserMessage(error)); } }
  return <div className="space-y-10"><div className="flex items-center justify-between"><Button asChild size="sm" variant="ghost"><Link to="/cards"><ArrowLeft className="size-4" />Tarjetas</Link></Button><ActionMenu items={[{ icon: <Settings2 className="size-4" />, label: "Editar tarjeta", onSelect: () => setEditOpen(true) }, current.is_active ? { icon: <Archive className="size-4" />, label: "Archivar", onSelect: () => setArchiveOpen(true), tone: "danger" } : { icon: <ArchiveRestore className="size-4" />, label: "Restaurar", onSelect: () => void toggleActive(true) }]} /></div>
    <section className="grid gap-8 border-b border-border/70 pb-10 lg:grid-cols-[minmax(0,1.2fr)_minmax(300px,.8fr)]"><div><p className="text-sm font-medium text-primary">{current.issuer}{!current.is_active ? " · Archivada" : ""}</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.04em]">{current.name}</h1><p className="mt-2 font-mono text-sm text-muted-foreground">•••• {current.last4 ?? "Nexo"} · {current.currency}</p><p className="mt-10 text-xs uppercase tracking-[0.14em] text-muted-foreground">Saldo utilizado</p><MoneyValue amount={current.used_balance_minor} className="mt-2 block text-[clamp(3rem,8vw,5.5rem)] leading-none tracking-[-0.065em]" currency={current.currency} /></div><div className={`rounded-[1.6rem] bg-gradient-to-br p-6 shadow-card ${theme.className}`}><p className="text-xs text-white/65">Disponible</p><MoneyValue amount={current.available_credit_minor} className="mt-1 block text-3xl text-white" currency={current.currency} /><div className="mt-8 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-white/80" style={{ width: `${Math.min(100, utilization)}%` }} /></div><div className="mt-3 flex justify-between text-xs text-white/70"><span>{utilization.toFixed(1)}% utilizado</span><span>Límite <MoneyValue amount={current.credit_limit_minor} className="text-white" currency={current.currency} size="sm" /></span></div></div></section>
    <section className="grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2 lg:grid-cols-4"><Metric label="Pago actual" value={<MoneyValue amount={current.current_payment_minor ?? "0"} currency={current.currency} />} detail={current.current_payment_due_date ? `Límite ${formatFinancialDate(current.current_payment_due_date, "dd MMM")}` : "Sin estado cerrado"} /><Metric label="Acumulado del ciclo" value={<MoneyValue amount={current.open_cycle_accumulated_minor} currency={current.currency} />} detail="No es pago requerido" /><Metric label="Próximo corte" value={formatFinancialDate(current.next_statement_date, "dd MMM yyyy")} detail={`Límite estimado ${formatFinancialDate(current.next_payment_due_date, "dd MMM")}`} /><Metric label="Disponible" value={<MoneyValue amount={current.available_credit_minor} currency={current.currency} />} detail={`Utilización ${utilization.toFixed(1)}%`} /></section>
    <section><div className="mb-5 flex items-end justify-between gap-4"><div><h2 className="text-xl font-semibold">Estados de cuenta</h2><p className="mt-1 text-sm text-muted-foreground">Snapshots cerrados; el ciclo actual permanece separado.</p></div>{current.is_active ? <Button onClick={() => setCloseOpen(true)} size="sm" variant="secondary"><CalendarClock className="size-4" />Cerrar estado</Button> : null}</div>{statements.isPending ? <StatementsSkeleton /> : statements.data?.length ? <div className="divide-y divide-border border-y border-border">{statements.data.map((statement) => <button className="flex min-h-20 w-full items-center justify-between gap-4 py-4 text-left hover:bg-surface-secondary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30" key={statement.id} onClick={() => setSelected(statement)} type="button"><div><p className="font-semibold">Corte {formatFinancialDate(statement.statement_date, "dd MMM yyyy")}</p><p className="mt-1 text-xs text-muted-foreground">Fecha límite {formatFinancialDate(statement.payment_due_date, "dd MMM yyyy")} · {statement.status === "paid" ? "Pagado" : "Cerrado"}</p></div><MoneyValue amount={statement.statement_balance_minor} currency={current.currency} /></button>)}</div> : <EmptyState description="El ciclo abierto todavía no es un pago requerido. Ciérralo manualmente cuando quieras crear el snapshot." title="Sin estados cerrados" />}</section>
    <CardFormSheet baseCurrency={current.currency} card={current} onOpenChange={setEditOpen} open={editOpen} />{cycle.data ? <CloseStatementDialog card={current} cycle={cycle.data} onOpenChange={setCloseOpen} open={closeOpen} /> : null}<StatementDetailSheet currency={current.currency} onOpenChange={(open) => { if (!open) setSelected(undefined); }} open={Boolean(selected)} statement={selected} /><ConfirmDialog confirmLabel="Archivar tarjeta" description="Saldrá de selectores nuevos, pero conservará baseline, estados e historial." isPending={setActive.isPending} onConfirm={() => void toggleActive(false)} onOpenChange={setArchiveOpen} open={archiveOpen} title="¿Archivar esta tarjeta?" />
  </div>;
}
function Metric({ detail, label, value }: { detail: string; label: string; value: React.ReactNode }) { return <div className="bg-surface p-5"><p className="text-xs font-medium text-muted-foreground">{label}</p><div className="mt-2 text-xl font-semibold">{value}</div><p className="mt-2 text-xs text-muted-foreground">{detail}</p></div>; }
