import { Archive, ArchiveRestore, ArrowLeft, CalendarClock, CreditCard, HandCoins, RotateCcw, Settings2 } from "lucide-react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";

import { ActionMenu } from "@/components/action-menu";
import { ContextHelp } from "@/components/context-help";
import { EmptyState, ErrorState } from "@/components/feedback";
import { MoneyValue } from "@/components/money-value";
import { ConfirmDialog } from "@/components/sheet";
import { CardDetailSkeleton, CardMovementListSkeleton, CardStatementActivitySkeleton, StatementsSkeleton } from "@/components/skeletons";
import { Button } from "@/components/ui/button";
import { FilterBar, FilterPill } from "@/components/filter-bar";
import { useToast } from "@/components/toast";
import { useAccounts } from "@/hooks/use-accounts";
import { useCardStatementActivity, useCardTransactions } from "@/hooks/use-card-transactions";
import { useCard, useCards, useCardStatementCloseCandidate, useCardStatements, useSetCardActive } from "@/hooks/use-cards";
import { useInstallmentPlans } from "@/hooks/use-installments";
import { formatFinancialDate } from "@/lib/dates";
import { motionTokens } from "@/design-system/motion";
import { toUserMessage } from "@/lib/errors";
import type { CardStatement } from "@/types/database";
import { CardFormSheet } from "@/features/cards/card-form-sheet";
import { cardThemes, cardUtilization } from "@/features/cards/card-utils";
import { CloseStatementDialog } from "@/features/cards/close-statement-dialog";
import { StatementDetailSheet } from "@/features/cards/statement-detail-sheet";
import { CardPurchaseForm } from "@/features/cards/card-purchase-form";
import { CardPaymentForm } from "@/features/cards/card-payment-form";
import { CardRefundForm } from "@/features/cards/card-refund-form";
import { CardStatementActivity } from "@/features/cards/card-statement-activity";
import { InstallmentPlansSection } from "@/features/cards/installment-plans-section";
import { MovementDetailSheet } from "@/features/movements/movement-detail-sheet";
import { MovementList } from "@/features/movements/movement-list";

export function CardDetailPage() {
  const { id } = useParams(); const card = useCard(id); const cards = useCards(); const accounts = useAccounts(); const closeCandidate = useCardStatementCloseCandidate(id); const statements = useCardStatements(id); const setActive = useSetCardActive(); const toast = useToast();
  const installmentPlans = useInstallmentPlans(id);
  const [movementKind, setMovementKind] = useState<"all" | "card_charge" | "installments" | "card_payment" | "card_refund">("all"); const movements = useCardTransactions(id, movementKind);
  const visibleStatementDates = Array.from(new Set([card.data?.next_statement_date, closeCandidate.data?.statement_date, ...(statements.data?.map((statement) => statement.statement_date) ?? [])].filter((date): date is string => Boolean(date))));
  const statementActivity = useCardStatementActivity(id, visibleStatementDates, movementKind);
  const reduceMotion = useReducedMotion();
  const [editOpen, setEditOpen] = useState(false); const [archiveOpen, setArchiveOpen] = useState(false); const [closeOpen, setCloseOpen] = useState(false); const [purchaseOpen, setPurchaseOpen] = useState(false); const [paymentOpen, setPaymentOpen] = useState(false); const [refundOpen, setRefundOpen] = useState(false); const [movementView, setMovementView] = useState<"date" | "statement">("date"); const [showAllStatements, setShowAllStatements] = useState(false); const [selectedEventId, setSelectedEventId] = useState<string>(); const [selectedPlanId, setSelectedPlanId] = useState<string>(); const [selected, setSelected] = useState<CardStatement>();
  if (card.isPending) return <CardDetailSkeleton />;
  if (card.isError || !card.data) return <ErrorState message={toUserMessage(card.error)} onRetry={() => void card.refetch()} />;
  const current = card.data; const utilization = cardUtilization(current.used_balance_minor, current.credit_limit_minor); const theme = cardThemes[current.visual_theme];
  async function toggleActive(active: boolean) { try { await setActive.mutateAsync({ cardId: current.id, active }); toast.success(active ? "Tarjeta restaurada" : "Tarjeta archivada"); setArchiveOpen(false); } catch (error) { toast.error(toUserMessage(error)); } }
  function openActivity(eventId: string) { const plan = installmentPlans.data?.find((item) => item.purchase_event_id === eventId); const activity = movements.data?.find((movement) => movement.event_id === eventId); if (plan?.id || activity?.installment_plan_id) setSelectedPlanId(plan?.id ?? activity?.installment_plan_id ?? undefined); else setSelectedEventId(eventId); }
  return <div className="space-y-10"><div className="flex items-center justify-between"><Button asChild size="sm" variant="ghost"><Link to="/cards"><ArrowLeft className="size-4" />Tarjetas</Link></Button><ActionMenu items={[{ icon: <RotateCcw className="size-4" />, label: "Registrar reembolso", onSelect: () => setRefundOpen(true) }, { icon: <Settings2 className="size-4" />, label: "Editar tarjeta", onSelect: () => setEditOpen(true) }, current.is_active ? { icon: <Archive className="size-4" />, label: "Archivar", onSelect: () => setArchiveOpen(true), tone: "danger" } : { icon: <ArchiveRestore className="size-4" />, label: "Restaurar", onSelect: () => void toggleActive(true) }]} /></div>
    <section className="grid gap-8 border-b border-border/70 pb-10 lg:grid-cols-[minmax(0,1.2fr)_minmax(300px,.8fr)]"><div><p className="text-sm font-medium text-primary">{current.issuer}{!current.is_active ? " · Archivada" : ""}</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.04em]">{current.name}</h1><p className="mt-2 font-mono text-sm text-muted-foreground">•••• {current.last4 ?? "Nexo"} · {current.currency}</p><div className="mt-10 flex items-center gap-1"><p className="text-xs uppercase tracking-[0.14em] text-muted-foreground">Saldo utilizado</p><ContextHelp label="saldo utilizado" text="Es todo el crédito que estás usando actualmente. Puede incluir compras a meses que pagarás más adelante." /></div><MoneyValue amount={current.used_balance_minor} className="mt-2 block text-[clamp(3rem,8vw,5.5rem)] leading-none tracking-[-0.065em]" currency={current.currency} /></div><div className={`rounded-[1.6rem] bg-gradient-to-br p-6 shadow-card ${theme.className}`}><p className="text-xs text-white/65">Disponible</p><MoneyValue amount={current.available_credit_minor} className="mt-1 block text-3xl text-white" currency={current.currency} /><div className="mt-8 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-white/80" style={{ width: `${Math.min(100, utilization)}%` }} /></div><div className="mt-3 flex justify-between text-xs text-white/70"><span>{utilization.toFixed(1)}% utilizado</span><span>Límite <MoneyValue amount={current.credit_limit_minor} className="text-white" currency={current.currency} size="sm" /></span></div></div></section>
    {current.is_active ? <section className="flex flex-wrap gap-3"><Button onClick={() => setPurchaseOpen(true)}><CreditCard className="size-4" />Nueva compra</Button><Button onClick={() => setPaymentOpen(true)} variant="secondary"><HandCoins className="size-4" />Pagar tarjeta</Button></section> : null}
    <section className="grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2 lg:grid-cols-4"><Metric label="Pago de este estado" value={<MoneyValue amount={current.current_payment_minor ?? "0"} currency={current.currency} />} detail={current.current_payment_due_date ? `Fecha límite ${formatFinancialDate(current.current_payment_due_date, "dd MMM")}` : "No tienes un estado pendiente"} help="Es lo que todavía falta pagar del último estado de cuenta cerrado." /><Metric label="Próximo estado" value={<MoneyValue amount={current.open_cycle_accumulated_minor} currency={current.currency} />} detail="Estimado hasta ahora" help="Es el total estimado para tu siguiente corte. Puede cambiar mientras el periodo siga abierto." /><Metric label="Corte" value={formatFinancialDate(current.next_statement_date, "dd MMM yyyy")} detail={`Fecha límite estimada ${formatFinancialDate(current.next_payment_due_date, "dd MMM")}`} help="Ese día termina el periodo actual y comienza uno nuevo." /><Metric label="Disponible" value={<MoneyValue amount={current.available_credit_minor} currency={current.currency} />} detail={`${utilization.toFixed(1)}% del límite utilizado`} help="Es el crédito que todavía puedes usar según el saldo actual de Nexo." /></section>
    <InstallmentPlansSection cardId={current.id} cards={cards.data ?? [current]} currency={current.currency} currentStatementDate={current.next_statement_date} onSelectedPlanIdChange={setSelectedPlanId} {...(selectedPlanId ? { selectedPlanId } : {})} />
    <section><div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold">Movimientos</h2><p className="mt-1 text-sm text-muted-foreground">Compras, pagos y reembolsos de esta tarjeta.</p></div><div className="flex gap-2"><Button onClick={() => setMovementView("date")} size="sm" variant={movementView === "date" ? "secondary" : "ghost"}>Por fecha</Button><Button onClick={() => setMovementView("statement")} size="sm" variant={movementView === "statement" ? "secondary" : "ghost"}>Por estado</Button></div></div><FilterBar>{(["all", "card_charge", "installments", "card_payment", "card_refund"] as const).map((value) => <FilterPill active={movementKind === value} key={value} onClick={() => setMovementKind(value)}>{value === "all" ? "Todos" : value === "card_charge" ? "Compras" : value === "installments" ? "MSI" : value === "card_payment" ? "Pagos" : "Reembolsos"}</FilterPill>)}</FilterBar><div className="mt-5"><AnimatePresence initial={false} mode="wait"><motion.div animate={{ opacity: 1, y: 0 }} exit={reduceMotion ? { opacity: 0 } : { opacity: 0, y: -4 }} initial={reduceMotion ? false : { opacity: 0, y: 4 }} key={movementView} layout transition={{ duration: reduceMotion ? 0 : motionTokens.duration.fast, ease: motionTokens.ease.standard }}>{movementView === "date" ? movements.isPending ? <CardMovementListSkeleton /> : movements.data?.length ? <MovementList movements={movements.data} onSelect={openActivity} /> : <EmptyState description="Usa las acciones superiores para registrar la primera compra, pago o devolución." title="Aún no hay movimientos" /> : statementActivity.isPending ? <CardStatementActivitySkeleton /> : statementActivity.data?.length ? <CardStatementActivity closedStatementDates={statements.data?.map((statement) => statement.statement_date) ?? []} currency={current.currency} openStatementDate={current.next_statement_date} {...(closeCandidate.data?.statement_date ? { pendingStatementDate: closeCandidate.data.statement_date } : {})} segments={statementActivity.data} onSelect={openActivity} /> : <EmptyState description="Las mensualidades de otros periodos siguen disponibles dentro del detalle de cada MSI." title="Este periodo todavía no tiene movimientos" />}</motion.div></AnimatePresence></div></section>
    <section><div className="mb-5 flex items-end justify-between gap-4"><div><h2 className="text-xl font-semibold">Estados de cuenta</h2><p className="mt-1 text-sm text-muted-foreground">Consulta lo que cerró, lo que pagaste y lo que falta.</p></div>{current.is_active ? <Button disabled={closeCandidate.isPending || !closeCandidate.data} onClick={() => setCloseOpen(true)} size="sm" variant="secondary"><CalendarClock className="size-4" />Cerrar estado</Button> : null}</div>{statements.isPending ? <StatementsSkeleton /> : statements.data?.length ? <><div className="divide-y divide-border border-y border-border">{(showAllStatements ? statements.data : statements.data.slice(0, 5)).map((statement) => <button className="flex min-h-20 w-full items-center justify-between gap-4 py-4 text-left hover:bg-surface-secondary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30" key={statement.id} onClick={() => setSelected(statement)} type="button"><div><p className="font-semibold">Estado de {formatFinancialDate(statement.statement_date, "MMMM yyyy")}</p><p className="mt-1 text-xs text-muted-foreground">Fecha límite {formatFinancialDate(statement.payment_due_date, "dd MMM yyyy")} · {statement.status === "paid" ? "Pagado" : "Pendiente"}</p></div><MoneyValue amount={statement.statement_balance_minor} currency={current.currency} /></button>)}</div>{statements.data.length > 5 ? <Button className="mt-3" onClick={() => setShowAllStatements((value) => !value)} size="sm" variant="ghost">{showAllStatements ? "Ver menos" : "Ver todos"}</Button> : null}</> : <EmptyState description={closeCandidate.data ? `Ya puedes cerrar el periodo que terminó el ${formatFinancialDate(closeCandidate.data.statement_date, "dd MMM yyyy")}.` : "Cuando cierres tu primer periodo, aparecerá aquí."} title="Aún no hay estados de cuenta" />}</section>
    <CardPurchaseForm cards={cards.data ?? [current]} defaultCardId={current.id} onOpenChange={setPurchaseOpen} open={purchaseOpen} /><CardPaymentForm accounts={accounts.data ?? []} cards={cards.data ?? [current]} defaultCardId={current.id} onOpenChange={setPaymentOpen} open={paymentOpen} /><CardRefundForm cards={cards.data ?? [current]} defaultCardId={current.id} onOpenChange={setRefundOpen} open={refundOpen} /><MovementDetailSheet accounts={accounts.data ?? []} eventId={selectedEventId} onEventIdChange={setSelectedEventId} onOpenChange={(open) => { if (!open) setSelectedEventId(undefined); }} open={Boolean(selectedEventId)} /><CardFormSheet baseCurrency={current.currency} card={current} onOpenChange={setEditOpen} open={editOpen} />{closeCandidate.data ? <CloseStatementDialog candidate={closeCandidate.data} card={current} onOpenChange={setCloseOpen} open={closeOpen} /> : null}<StatementDetailSheet currency={current.currency} onOpenChange={(open) => { if (!open) setSelected(undefined); }} open={Boolean(selected)} statement={selected} /><ConfirmDialog confirmLabel="Archivar tarjeta" description="Saldrá de selectores nuevos, pero conservará su punto de inicio, estados e historial." isPending={setActive.isPending} onConfirm={() => void toggleActive(false)} onOpenChange={setArchiveOpen} open={archiveOpen} title="¿Archivar esta tarjeta?" />
  </div>;
}
function Metric({ detail, help, label, value }: { detail: string; help: string; label: string; value: React.ReactNode }) { return <div className="bg-surface p-5"><div className="flex items-center gap-1"><p className="text-xs font-medium text-muted-foreground">{label}</p><ContextHelp label={label.toLocaleLowerCase("es-MX")} text={help} /></div><div className="mt-2 text-xl font-semibold">{value}</div><p className="mt-2 text-xs text-muted-foreground">{detail}</p></div>; }
