import { zodResolver } from "@hookform/resolvers/zod";
import { format } from "date-fns";
import { useEffect } from "react";
import { useForm, type UseFormRegisterReturn } from "react-hook-form";

import { FormField } from "@/components/form-field";
import { ResponsiveDialog } from "@/components/responsive-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { useToast } from "@/components/toast";
import { useCreateCardPurchase, useUpdateCardPurchase } from "@/hooks/use-card-transactions";
import { useCreateInstallmentPurchase } from "@/hooks/use-installments";
import { purchaseStartDateError } from "@/features/cards/card-operation-utils";
import { useCategories } from "@/hooks/use-movements";
import { toUserMessage } from "@/lib/errors";
import { formatFinancialDate } from "@/lib/dates";
import { minorToDisplay, parseMoneyInput, splitPrincipalIntoInstallments } from "@/lib/money";
import { cardPurchaseSchema, resolveInstallmentCount, standardInstallmentTerms, type CardPurchaseInput } from "@/schemas/card-transaction";
import type { CardSummary, FinancialActivity } from "@/types/database";
import { PurchaseSplitFields } from "@/features/people/purchase-split-fields";
import { resolvePurchaseSplit } from "@/lib/purchase-split";

const paymentMethods = [
  ["", "Sin especificar"], ["physical_card", "Tarjeta física"], ["apple_pay", "Apple Pay"],
  ["google_pay", "Google Pay"], ["online", "Compra en línea"], ["other", "Otro"],
] as const;

export function CardPurchaseForm({ cards, defaultCardId, defaultContactId, existing, prefill, onOpenChange, onUpdated, open }: { cards: CardSummary[]; defaultCardId?: string | undefined; defaultContactId?: string | undefined; existing?: FinancialActivity | undefined; prefill?: FinancialActivity | undefined; onOpenChange: (open: boolean) => void; onUpdated?: ((eventId: string) => void) | undefined; open: boolean }) {
  const categories = useCategories(); const create = useCreateCardPurchase(); const createInstallment = useCreateInstallmentPurchase(); const update = useUpdateCardPurchase(existing?.event_id ?? "missing"); const toast = useToast();
  const source = existing ?? prefill;
  const form = useForm<CardPurchaseInput>({ resolver: zodResolver(cardPurchaseSchema), defaultValues: defaults(cards, defaultCardId, defaultContactId) });
  useEffect(() => { form.reset(source ? { amount: minorToDisplay(BigInt(source.amount_minor)), purchase_type: "single", installment_count: "12", custom_installment_count: "", installment_amount: "", card_id: source.card_id ?? defaultCardId ?? "", category_id: source.category_id ?? "other_expense", occurred_on: prefill ? format(new Date(), "yyyy-MM-dd") : source.occurred_on, description: source.description, payment_method: source.payment_method ?? "", notes: source.notes ?? "", purchase_scope: source.third_party_allocations?.length ? (BigInt(source.personal_amount_minor) === 0n ? "other" : "shared") : "self", personal_amount: minorToDisplay(BigInt(source.personal_amount_minor)), allocations: source.third_party_allocations?.map((item) => ({ contact_id: item.contact_id, amount: minorToDisplay(BigInt(item.amount_minor)) })) ?? [] } : defaults(cards, defaultCardId, defaultContactId)); }, [cards, defaultCardId, defaultContactId, form, open, prefill, source]);
  const selectedCard = cards.find((card) => card.id === form.watch("card_id"));
  const purchaseType = form.watch("purchase_type"); const installmentOption = form.watch("installment_count"); const customCount = form.watch("custom_installment_count"); const installmentCount = resolveInstallmentCount({ installment_count: installmentOption, custom_installment_count: customCount }); const amount = form.watch("amount"); const customInstallment = form.watch("installment_amount");
  let schedule: bigint[] = []; try { if (purchaseType === "installments") schedule = splitPrincipalIntoInstallments(parseMoneyInput(amount), installmentCount, customInstallment.trim() ? parseMoneyInput(customInstallment) : undefined); } catch { schedule = []; }
  async function submit(input: CardPurchaseInput) { try { if (parseMoneyInput(input.amount) <= 0n) { form.setError("amount", { message: "El importe debe ser mayor que cero." }); return; } if (existing && input.purchase_type === "installments") { form.setError("root", { message: "Para convertir una compra existente a MSI, revierte y registra un plan nuevo." }); return; } resolvePurchaseSplit(input); if (input.purchase_type === "installments") splitPrincipalIntoInstallments(parseMoneyInput(input.amount), resolveInstallmentCount(input), input.installment_amount.trim() ? parseMoneyInput(input.installment_amount) : undefined); const targetCard = cards.find((card) => card.id === input.card_id); const startError = targetCard ? purchaseStartDateError(input.occurred_on, targetCard.baseline_date) : null; if (startError) { form.setError("occurred_on", { message: startError.field }); form.setError("root", { message: startError.message }); return; } const id = existing ? await update.mutateAsync(input) : input.purchase_type === "installments" ? await createInstallment.mutateAsync(input) : await create.mutateAsync(input); if (existing) onUpdated?.(id); toast.success(existing ? "Compra actualizada" : input.purchase_type === "installments" ? "Compra MSI registrada" : "Compra registrada"); onOpenChange(false); } catch (error) { form.setError("root", { message: toUserMessage(error) }); } }
  const activeCards = cards.filter((card) => card.is_active || card.id === existing?.card_id); const mutation = existing ? update : purchaseType === "installments" ? createInstallment : create;
  return <ResponsiveDialog description={existing ? "Nexo actualizará la compra y conservará el cambio en tu historial. Las compras de estados cerrados no pueden editarse." : "La compra usará crédito de la tarjeta y no moverá dinero de tus cuentas."} footer={<><Button onClick={() => onOpenChange(false)} variant="ghost">Cancelar</Button><Button disabled={mutation.isPending} form="card-purchase-form" type="submit">{mutation.isPending ? "Guardando…" : existing ? "Guardar cambios" : "Registrar compra"}</Button></>} onOpenChange={onOpenChange} open={open} size="medium" title={existing ? "Editar compra" : "Nueva compra"}>
    <form className="space-y-6" id="card-purchase-form" onSubmit={(event) => void form.handleSubmit(submit)(event)}>
      <MoneyInput error={form.formState.errors.amount?.message} register={form.register("amount")} />
      {!existing ? <div><p className="mb-2 text-sm font-medium">Forma de pago</p><div className="grid grid-cols-2 gap-2 rounded-xl bg-surface-secondary p-1"><Button onClick={() => form.setValue("purchase_type", "single", { shouldValidate: true })} type="button" variant={purchaseType === "single" ? "secondary" : "ghost"}>Una sola exhibición</Button><Button onClick={() => form.setValue("purchase_type", "installments", { shouldValidate: true })} type="button" variant={purchaseType === "installments" ? "secondary" : "ghost"}>Meses sin intereses</Button></div></div> : null}
      {purchaseType === "installments" && !existing ? <div className="grid gap-5 rounded-2xl border border-primary/15 bg-primary-soft/35 p-4 sm:grid-cols-2"><FormField error={form.formState.errors.installment_count?.message} id="installment-count" label="Plazo"><Select id="installment-count" {...form.register("installment_count")}>{standardInstallmentTerms.map((count) => <option key={count} value={count}>{count} meses</option>)}<option value="custom">Personalizado</option></Select></FormField>{installmentOption === "custom" ? <FormField error={form.formState.errors.custom_installment_count?.message} hint="Entre 2 y 60 meses." id="custom-installment-count" label="Número de meses"><Input id="custom-installment-count" inputMode="numeric" min={2} max={60} type="number" {...form.register("custom_installment_count")} /></FormField> : <div className="hidden sm:block" />}<FormField hint="Opcional. Si hay diferencia por redondeo, se ajustará la última." id="installment-amount" label="Mensualidad del banco"><Input id="installment-amount" inputMode="decimal" placeholder={schedule[0] ? minorToDisplay(schedule[0]) : "Calculada automáticamente"} {...form.register("installment_amount")} /></FormField>{schedule.length ? <div className="sm:col-span-2 text-xs text-muted-foreground"><span className="font-semibold text-foreground">{minorToDisplay(schedule[0] ?? 0n)} × {schedule.length - 1}</span> · última mensualidad <span className="font-semibold text-foreground">{minorToDisplay(schedule.at(-1) ?? 0n)}</span>. El saldo utilizado aumentará una sola vez por el importe total de la compra.</div> : null}</div> : null}
      <PurchaseSplitFields amount={form.watch("amount")} allocations={form.watch("allocations")} onAllocations={(value) => form.setValue("allocations", value, { shouldValidate: true })} onPersonalAmount={(value) => form.setValue("personal_amount", value, { shouldValidate: true })} onScope={(value) => form.setValue("purchase_scope", value, { shouldValidate: true })} personalAmount={form.watch("personal_amount")} scope={form.watch("purchase_scope")} />
      <div className="grid gap-5 sm:grid-cols-2"><FormField error={form.formState.errors.card_id?.message} hint={selectedCard ? `Controlada en Nexo desde ${formatFinancialDate(selectedCard.baseline_date, "dd MMM yyyy")}` : undefined} id="purchase-card" label="Tarjeta"><Select id="purchase-card" {...form.register("card_id")}>{activeCards.map((card) => <option key={card.id} value={card.id}>{card.name} · {card.currency}</option>)}</Select></FormField><FormField error={form.formState.errors.category_id?.message} id="purchase-category" label="Categoría"><Select id="purchase-category" {...form.register("category_id")}>{categories.data?.filter((item) => item.kind !== "income").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField></div>
      <div className="grid gap-5 sm:grid-cols-2"><FormField error={form.formState.errors.occurred_on?.message} id="purchase-date" label="Fecha"><Input id="purchase-date" type="date" {...form.register("occurred_on")} /></FormField><FormField id="purchase-method" label="Método de pago (opcional)"><Select id="purchase-method" {...form.register("payment_method")}>{paymentMethods.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></FormField></div>
      <FormField error={form.formState.errors.description?.message} id="purchase-description" label="Descripción"><Input id="purchase-description" placeholder="Starbucks" {...form.register("description")} /></FormField>
      <FormField error={form.formState.errors.notes?.message} id="purchase-notes" label="Notas (opcional)"><textarea className="min-h-24 w-full resize-none rounded-xl border border-border bg-surface px-3.5 py-3 text-sm outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/20" id="purchase-notes" {...form.register("notes")} /></FormField>
      {form.formState.errors.root ? <p className="text-sm text-danger" role="alert">{form.formState.errors.root.message}</p> : null}
    </form>
  </ResponsiveDialog>;
}

function defaults(cards: CardSummary[], cardId?: string, contactId?: string): CardPurchaseInput { return { amount: "", purchase_type: "single", installment_count: "12", custom_installment_count: "", installment_amount: "", card_id: cardId ?? cards.find((card) => card.is_active)?.id ?? "", category_id: "other_expense", occurred_on: format(new Date(), "yyyy-MM-dd"), description: "", payment_method: "", notes: "", purchase_scope: contactId ? "other" : "self", personal_amount: contactId ? "0" : "", allocations: contactId ? [{ contact_id: contactId, amount: "" }] : [] }; }
function MoneyInput({ error, register }: { error: string | undefined; register: UseFormRegisterReturn }) { return <FormField error={error} id="purchase-amount" label="Importe"><div className="relative"><span className="pointer-events-none absolute left-0 top-1/2 -translate-y-1/2 text-3xl text-muted-foreground">$</span><Input autoFocus className="h-20 rounded-none border-x-0 border-t-0 bg-transparent pl-7 text-5xl font-semibold shadow-none focus-visible:ring-0" id="purchase-amount" inputMode="decimal" placeholder="0.00" {...register} /></div></FormField>; }
