import { CalendarClock, ChevronRight, FilePenLine, Plus, RotateCcw } from "lucide-react";
import { useEffect, useState } from "react";

import { EmptyState, ErrorState } from "@/components/feedback";
import { MoneyValue } from "@/components/money-value";
import { ResponsiveDialog } from "@/components/responsive-dialog";
import { ConfirmDialog } from "@/components/sheet";
import { InstallmentPlanDetailSkeleton, InstallmentPlansSkeleton } from "@/components/skeletons";
import { useToast } from "@/components/toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { useInstallmentPlan, useInstallmentPlans, useInstallmentSchedule, useReverseInstallmentPurchase, useUpdateInstallmentMetadata } from "@/hooks/use-installments";
import { useCategories } from "@/hooks/use-movements";
import { formatFinancialDate } from "@/lib/dates";
import { toUserMessage } from "@/lib/errors";
import type { CardSummary, CurrencyCode, InstallmentPlanSummary, InstallmentStatus } from "@/types/database";
import { HistoricalInstallmentForm } from "@/features/cards/historical-installment-form";
import { installmentPeriodLabel, installmentTotalForStatement } from "@/features/cards/installment-presentation";

export function InstallmentPlansSection({ cardId, cards, currency, currentStatementDate, onSelectedPlanIdChange, selectedPlanId }: { cardId: string; cards: CardSummary[]; currency: CurrencyCode; currentStatementDate: string; onSelectedPlanIdChange: (planId: string | undefined) => void; selectedPlanId?: string }) {
  const plans = useInstallmentPlans(cardId);
  const [historicalOpen, setHistoricalOpen] = useState(false);
  const newPlans = plans.data?.filter((plan) => plan.origin === "new") ?? []; const historicalPlans = plans.data?.filter((plan) => plan.origin === "historical") ?? [];
  const periodTotal = installmentTotalForStatement(plans.data ?? [], currentStatementDate);
  return <section><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-xl font-semibold">Meses sin intereses</h2><p className="mt-1 text-sm text-muted-foreground">Ve cuánto toca pagar en este periodo y cuánto falta de cada plan.</p></div><Button onClick={() => setHistoricalOpen(true)} size="sm" variant="secondary"><Plus className="size-4" />Agregar MSI existente</Button></div>
    {plans.isPending ? <InstallmentPlansSkeleton /> : plans.isError ? <ErrorState message={toUserMessage(plans.error)} onRetry={() => void plans.refetch()} /> : plans.data?.length ? <><InstallmentPeriodSummary amount={periodTotal} currency={currency} statementDate={currentStatementDate} /><div className="space-y-7">{newPlans.length ? <PlanGroup currentStatementDate={currentStatementDate} label="Compras hechas en Nexo" plans={newPlans} onSelect={onSelectedPlanIdChange} /> : null}{historicalPlans.length ? <PlanGroup currentStatementDate={currentStatementDate} label="Ya existían al empezar" plans={historicalPlans} onSelect={onSelectedPlanIdChange} /> : null}</div></> : <EmptyState description="Cuando registres una compra a meses, aparecerá aquí." title="No tienes MSI activos" />}
    <InstallmentPlanDetail currency={currency} currentStatementDate={currentStatementDate} onOpenChange={(open) => { if (!open) onSelectedPlanIdChange(undefined); }} open={Boolean(selectedPlanId)} {...(selectedPlanId ? { planId: selectedPlanId } : {})} />
    <HistoricalInstallmentForm cards={cards} defaultCardId={cardId} onOpenChange={setHistoricalOpen} open={historicalOpen} />
  </section>;
}

export function InstallmentPeriodSummary({ amount, currency, statementDate }: { amount: bigint | string; currency: CurrencyCode; statementDate: string }) { return <div className="mb-7 flex items-center justify-between gap-5 rounded-2xl bg-primary-soft px-5 py-4"><div><p className="text-sm font-semibold text-primary-strong">MSI de este periodo</p><p className="mt-1 text-xs text-muted-foreground">Corte {formatFinancialDate(statementDate, "dd MMM")}</p></div><MoneyValue amount={amount} className="text-2xl text-primary-strong" currency={currency} /></div>; }

function PlanGroup({ currentStatementDate, label, onSelect, plans }: { currentStatementDate: string; label: string; onSelect: (id: string) => void; plans: InstallmentPlanSummary[] }) { return <div><p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">{label}</p><div className="grid gap-3 md:grid-cols-2">{plans.map((plan) => <InstallmentPlanCard currentStatementDate={currentStatementDate} key={plan.id} onClick={() => onSelect(plan.id)} plan={plan} />)}</div></div>; }

export function InstallmentPlanCard({ currentStatementDate, onClick, plan }: { currentStatementDate: string; onClick: () => void; plan: InstallmentPlanSummary }) {
  const progress = plan.installment_count ? (plan.paid_count / plan.installment_count) * 100 : 0;
  const periodLabel = installmentPeriodLabel(plan.next_statement_date, currentStatementDate);
  return <button aria-label={`Ver detalle de ${plan.description}`} className="group rounded-2xl border border-border bg-surface p-5 text-left transition hover:border-primary/30 hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30" onClick={onClick} type="button"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="truncate font-semibold">{plan.description}</p><p className="mt-1 text-xs font-medium text-primary">{plan.installment_count} MSI{plan.origin === "historical" ? " · Existente" : ""}</p></div><ChevronRight className="mt-1 size-4 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5 motion-reduce:transition-none" /></div><div className="mt-5 rounded-xl bg-surface-secondary p-4"><p className="text-xs font-medium text-muted-foreground">{periodLabel}</p>{plan.current_installment_number && plan.current_installment_minor ? <><div className="mt-2 flex items-baseline justify-between gap-4"><p className="text-xl font-semibold tracking-tight">{plan.current_installment_number} de {plan.installment_count}</p><MoneyValue amount={plan.current_installment_minor} className="text-2xl" currency={plan.currency} /></div>{plan.next_statement_date ? <p className="mt-2 text-xs text-muted-foreground">Corte <span className="font-semibold text-foreground">{formatFinancialDate(plan.next_statement_date, "dd MMM")}</span></p> : null}</> : <p className="mt-2 font-semibold">Plan cubierto</p>}</div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-surface-secondary"><div className="h-full rounded-full bg-primary transition-[width] motion-reduce:transition-none" style={{ width: `${progress}%` }} /></div><div className="mt-4 grid grid-cols-2 gap-5"><div><p className="text-xs text-muted-foreground">Pagadas</p><p className="mt-1 text-sm font-semibold">{plan.paid_count} de {plan.installment_count}</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Te falta pagar</p><MoneyValue amount={plan.remaining_principal_minor} className="mt-1 block text-sm" currency={plan.currency} size="sm" /></div></div>{plan.origin === "historical" ? <p className="mt-4 text-xs text-muted-foreground">{plan.included_in_opening_balance ? "Ya incluido en el saldo de tu tarjeta" : "Pendiente agregado al registrar el plan"}</p> : null}</button>;
}

function InstallmentPlanDetail({ currency, currentStatementDate, onOpenChange, open, planId }: { currency: CurrencyCode; currentStatementDate: string; onOpenChange: (open: boolean) => void; open: boolean; planId?: string }) {
  const plan = useInstallmentPlan(planId); const schedule = useInstallmentSchedule(planId); const categories = useCategories(); const reverse = useReverseInstallmentPurchase(); const toast = useToast();
  const [edit, setEdit] = useState(false); const [confirm, setConfirm] = useState(false); const [description, setDescription] = useState(""); const [categoryId, setCategoryId] = useState(""); const [notes, setNotes] = useState("");
  const update = useUpdateInstallmentMetadata(planId ?? "missing");
  useEffect(() => { if (plan.data) { setDescription(plan.data.description); setCategoryId(plan.data.category_id ?? ""); setNotes(plan.data.notes ?? ""); } }, [plan.data]);
  async function save() { if (!description.trim()) return; try { await update.mutateAsync({ description: description.trim(), categoryId: categoryId || null, notes }); toast.success("Plan MSI actualizado"); setEdit(false); } catch (error) { toast.error(toUserMessage(error)); } }
  async function reversePlan() { if (!planId) return; try { await reverse.mutateAsync(planId); toast.success("Compra MSI revertida"); setConfirm(false); onOpenChange(false); } catch (error) { toast.error(toUserMessage(error)); } }
  const current = plan.data;
  const currentSchedule = schedule.data?.find((item) => item.installment_number === current?.current_installment_number);
  const followingSchedule = currentSchedule ? schedule.data?.find((item) => item.installment_number === currentSchedule.installment_number + 1) : undefined;
  return <><ResponsiveDialog description="Una mensualidad se marca como pagada cuando cubres el estado de cuenta correspondiente." footer={current ? <><Button onClick={() => setEdit((value) => !value)} variant="ghost"><FilePenLine className="size-4" />{edit ? "Cancelar" : "Editar información"}</Button><Button onClick={() => setConfirm(true)} variant="danger"><RotateCcw className="size-4" />{current.origin === "historical" ? "Eliminar MSI existente" : "Revertir compra MSI"}</Button></> : null} onOpenChange={onOpenChange} open={open} size="large" title="Detalle del MSI">
    {plan.isPending || schedule.isPending ? <InstallmentPlanDetailSkeleton /> : plan.isError || schedule.isError || !current ? <ErrorState message={toUserMessage(plan.error ?? schedule.error)} /> : <div className="space-y-7">
      <div><p className="text-sm text-muted-foreground">{current.installment_count} MSI{current.origin === "historical" ? " · Existente" : ""}</p><h3 className="mt-1 text-2xl font-semibold">{current.description}</h3></div>
      {edit ? <div className="space-y-3 rounded-2xl border border-border p-4"><Input aria-label="Descripción" maxLength={160} onChange={(event) => setDescription(event.target.value)} value={description} /><Select aria-label="Categoría" onChange={(event) => setCategoryId(event.target.value)} value={categoryId}><option value="">Sin categoría</option>{categories.data?.filter((item) => item.kind !== "income").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><textarea aria-label="Notas" className="min-h-24 w-full rounded-xl border border-border bg-surface p-3 text-sm" maxLength={2000} onChange={(event) => setNotes(event.target.value)} value={notes} /><Button disabled={update.isPending || !description.trim()} onClick={() => void save()}>{update.isPending ? "Guardando…" : "Guardar cambios"}</Button></div> : null}
      {currentSchedule ? <div className="grid gap-4 rounded-2xl bg-primary-soft p-5 sm:grid-cols-[minmax(0,1.25fr)_minmax(180px,.75fr)]"><div><p className="text-xs font-semibold text-primary-strong">{installmentPeriodLabel(current.next_statement_date, currentStatementDate)}</p><div className="mt-3 flex flex-wrap items-baseline gap-x-5 gap-y-2"><p className="text-3xl font-semibold tracking-tight">{currentSchedule.installment_number} de {current.installment_count}</p><MoneyValue amount={currentSchedule.reported_amount_minor} className="text-3xl text-primary-strong" currency={currency} /></div><p className="mt-3 text-sm text-muted-foreground">Corte <span className="font-semibold text-foreground">{formatFinancialDate(currentSchedule.due_statement_date, "dd MMM yyyy")}</span></p></div>{followingSchedule ? <div className="border-t border-primary/15 pt-4 sm:border-l sm:border-t-0 sm:pl-5 sm:pt-0"><p className="text-xs font-medium text-muted-foreground">Siguiente</p><p className="mt-2 font-semibold">{followingSchedule.installment_number} de {current.installment_count}</p><MoneyValue amount={followingSchedule.reported_amount_minor} className="mt-1 block" currency={currency} size="sm" /><p className="mt-2 text-xs text-muted-foreground">Corte {formatFinancialDate(followingSchedule.due_statement_date, "dd MMM")}</p></div> : null}</div> : <div className="rounded-2xl bg-success/10 p-5"><p className="font-semibold text-success">Todas las mensualidades están pagadas</p></div>}
      <div className="grid grid-cols-2 gap-x-8 gap-y-5 border-y border-border py-5 sm:grid-cols-3 lg:grid-cols-5"><Metric label="Importe original" value={<MoneyValue amount={current.original_amount_minor} currency={currency} size="sm" />} /><Metric label="Mensualidad" value={<MoneyValue amount={current.installment_amount_minor} currency={currency} size="sm" />} /><Metric label="Mensualidades pagadas" value={`${current.paid_count} de ${current.installment_count}`} /><Metric label="Te falta pagar" value={<MoneyValue amount={current.remaining_principal_minor} currency={currency} size="sm" />} /><Metric label="Tarjeta" value={current.card_name} />{current.origin === "historical" ? <><Metric label="Pagadas antes de Nexo" value={String(current.paid_before_nexo_count)} /><Metric label="Pagado antes de Nexo" value={<MoneyValue amount={current.reported_paid_amount_minor} currency={currency} size="sm" />} /><Metric label="Importe original pagado" value={<MoneyValue amount={current.principal_paid_before_nexo_minor} currency={currency} size="sm" />} /><Metric label="Deuda al agregarlo" value={current.included_in_opening_balance ? "Ya estaba incluida" : <MoneyValue amount={current.additional_card_impact_minor} currency={currency} size="sm" />} /></> : null}</div>
      <div className="grid gap-2 sm:grid-cols-2"><p className="text-sm text-muted-foreground"><CalendarClock className="mr-2 inline size-4" />Compra {formatFinancialDate(current.start_date, "dd MMM yyyy")}</p><p className="text-sm text-muted-foreground">El pago se deriva del estado de cuenta; no se registra otra operación por mensualidad.</p></div>
      <div><h4 className="mb-3 font-semibold">Cronograma completo</h4><div className="max-h-80 divide-y divide-border overflow-auto border-y border-border">{schedule.data?.map((item) => <div className="grid grid-cols-[1fr_auto] items-center gap-4 py-3" key={item.id}><div><p className="text-sm font-medium">Mensualidad {item.installment_number} de {current.installment_count}</p><p className="mt-1 text-xs text-muted-foreground">Estado: {formatFinancialDate(item.due_statement_date, "dd MMM yyyy")}</p><p className="mt-1 text-xs font-semibold text-foreground">{installmentStatusLabel(item.effective_status)}</p></div><MoneyValue amount={item.reported_amount_minor} currency={currency} size="sm" /></div>)}</div></div>
    </div>}
  </ResponsiveDialog><ConfirmDialog confirmLabel={current?.origin === "historical" ? "Eliminar MSI existente" : "Revertir compra MSI"} description={current?.origin === "historical" ? "Se quitará el plan y sus mensualidades futuras. Si Nexo agregó deuda al registrarlo, también restaurará el saldo. Tu historial se conservará." : "Se cancelará la compra y Nexo restaurará el saldo de la tarjeta. Las mensualidades futuras desaparecerán y el historial se conservará."} isPending={reverse.isPending} onConfirm={() => void reversePlan()} onOpenChange={setConfirm} open={confirm} title={current?.origin === "historical" ? "¿Eliminar este MSI existente?" : "¿Revertir esta compra a meses?"} /></>;
}

function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div><p className="text-xs text-muted-foreground">{label}</p><div className="mt-1 text-sm font-semibold">{value}</div></div>; }
function installmentStatusLabel(status: InstallmentStatus) { return status === "future" ? "Futura" : status === "pending" ? "Pendiente" : status === "paid_before_nexo" ? "Pagada antes de Nexo" : status === "paid" ? "Pagada" : "Revertida"; }
