import { MoneyValue } from "@/components/money-value";
import { Sheet } from "@/components/sheet";
import { formatFinancialDate } from "@/lib/dates";
import type { CardStatement, CurrencyCode } from "@/types/database";

export function StatementDetailSheet({ currency, onOpenChange, open, statement }: { currency: CurrencyCode; onOpenChange: (open: boolean) => void; open: boolean; statement: CardStatement | undefined }) {
  return <Sheet description="Snapshot bancario del periodo cerrado." onOpenChange={onOpenChange} open={open} title="Estado de cuenta">{statement ? <div className="space-y-1 rounded-2xl border border-border bg-surface-secondary p-5"><Row label="Periodo" value={`${formatFinancialDate(statement.cycle_start, "dd MMM yyyy")} → ${formatFinancialDate(statement.cycle_end, "dd MMM yyyy")}`} /><Row label="Corte" value={formatFinancialDate(statement.statement_date, "dd MMM yyyy")} /><Row label="Fecha límite" value={formatFinancialDate(statement.payment_due_date, "dd MMM yyyy")} /><MoneyRow amount={statement.statement_balance_minor} currency={currency} label="Saldo del estado" /><MoneyRow amount={statement.payment_to_avoid_interest_minor} currency={currency} label="Pago para no generar intereses" /><Row label="Pago mínimo" value={statement.minimum_payment_minor === null ? "No reportado" : <MoneyValue amount={statement.minimum_payment_minor} currency={currency} size="sm" />} /><MoneyRow amount={statement.amount_paid_minor} currency={currency} label="Pagado" /><MoneyRow amount={statement.remaining_due_minor} currency={currency} label="Restante" /><Row label="Estado" value={statement.status === "paid" ? "Pagado" : "Cerrado"} last /></div> : null}</Sheet>;
}
function Row({ label, last, value }: { label: string; last?: boolean; value: React.ReactNode }) { return <div className={`flex items-center justify-between gap-4 py-3 ${last ? "" : "border-b border-border/70"}`}><span className="text-xs font-medium text-muted-foreground">{label}</span><span className="text-right text-sm font-semibold">{value}</span></div>; }
function MoneyRow({ amount, currency, label }: { amount: string; currency: CurrencyCode; label: string }) { return <Row label={label} value={<MoneyValue amount={amount} currency={currency} size="sm" />} />; }
