import { MoneyValue } from "@/components/money-value";
import { Sheet } from "@/components/sheet";
import { formatFinancialDate } from "@/lib/dates";
import type { CardStatement, CurrencyCode } from "@/types/database";

export function StatementDetailSheet({ currency, onOpenChange, open, statement }: { currency: CurrencyCode; onOpenChange: (open: boolean) => void; open: boolean; statement: CardStatement | undefined }) {
  return <Sheet description="Resumen del periodo cerrado y sus pagos." onOpenChange={onOpenChange} open={open} title={statement ? `Estado de ${formatFinancialDate(statement.statement_date, "MMMM yyyy")}` : "Estado de cuenta"}>{statement ? <div className="divide-y divide-border/70"><Row label="Periodo" value={`${formatFinancialDate(statement.cycle_start, "dd MMM yyyy")} → ${formatFinancialDate(statement.cycle_end, "dd MMM yyyy")}`} /><Row label="Corte" value={formatFinancialDate(statement.statement_date, "dd MMM yyyy")} /><Row label="Fecha límite" value={formatFinancialDate(statement.payment_due_date, "dd MMM yyyy")} /><MoneyRow amount={statement.statement_balance_minor} currency={currency} label="Total del estado" /><MoneyRow amount={statement.payment_to_avoid_interest_minor} currency={currency} label="Para no generar intereses" /><Row label="Pago mínimo" value={statement.minimum_payment_minor === null ? "No registrado" : <MoneyValue amount={statement.minimum_payment_minor} currency={currency} size="sm" />} /><MoneyRow amount={statement.amount_paid_minor} currency={currency} label="Pagaste" /><MoneyRow amount={statement.remaining_due_minor} currency={currency} label="Falta por pagar" /><Row label="Estado" value={statement.status === "paid" ? "Pagado" : "Pendiente"} last /></div> : null}</Sheet>;
}
function Row({ label, last, value }: { label: string; last?: boolean; value: React.ReactNode }) { return <div className={`flex items-center justify-between gap-4 py-3 ${last ? "" : "border-b border-border/70"}`}><span className="text-xs font-medium text-muted-foreground">{label}</span><span className="text-right text-sm font-semibold">{value}</span></div>; }
function MoneyRow({ amount, currency, label }: { amount: string; currency: CurrencyCode; label: string }) { return <Row label={label} value={<MoneyValue amount={amount} currency={currency} size="sm" />} />; }
